--주석
/*
여러 줄 주석
여러 줄 작성 가능
*/

CREATE USER C##EMPLOYEE IDENTIFIED BY EMPLOYEE;     -- 계정만들기 C##EMPLOYEE 는 ID 뒤에 EMPLOYEE는 비번
GRANT RESOURCE, CONNECT TO C##EMPLOYEE;  --데베 접속하게 권한 허용
ALTER USER C##EMPLOYEE QUOTA UNLIMITED ON SYSTEM;    --사용자 작업 영역 할당
ALTER USER C##EMPLOYEE QUOTA UNLIMITED ON USERS;   --